name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Publish binaries
    runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: biliCount
            asset_name: biliCount-linux-amd64
          - os: windows-latest
            artifact_name: biliCount.exe
            asset_name: biliCount-windows-amd64
          - os: macos-latest
            artifact_name: biliCount
            asset_name: biliCount-macos-amd64

    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: v1.7.2
      - name: Build
        run: deno run -A ./scripts/build.ts
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          # A personal access token for the GitHub repository in which the release will be created and edited.
          # It is recommended to create the access token with the following scopes: `repo, user, admin:repo_hook`.
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true
